const mockApiService = {
  login: jest.fn(),
  register: jest.fn(),
  getCurrentUser: jest.fn(),
  getPlayers: jest.fn(),
  getPlayer: jest.fn(),
  createPlayer: jest.fn(),
  updatePlayer: jest.fn(),
  deletePlayer: jest.fn(),
  getUsers: jest.fn(),
  getUser: jest.fn(),
  createUser: jest.fn(),
  updateUser: jest.fn(),
  deleteUser: jest.fn(),
  getGames: jest.fn(),
  getGame: jest.fn(),
  createGame: jest.fn(),
  updateGame: jest.fn(),
  deleteGame: jest.fn(),
  getGameStats: jest.fn(),
  createGameStats: jest.fn(),
  updateGameStats: jest.fn(),
  deleteGameStats: jest.fn(),
  getAgentSessions: jest.fn(),
  createAgentSession: jest.fn(),
  getAgentSession: jest.fn(),
  updateAgentSession: jest.fn(),
  getAgentMessages: jest.fn(),
};

export default mockApiService;