name: Security Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes for testing

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
    - uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Set up Python for security scanning
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install pip-audit for Python vulnerability scanning
      run: pip install pip-audit

    - name: Run pip-audit on backend dependencies
      working-directory: ./backend
      run: |
        pip-audit -r requirements.txt --desc --format json > audit-results.json || true
        echo "=== Python Dependency Security Scan Results ==="
        pip-audit -r requirements.txt --desc || true
        echo "=== End of Security Scan ==="

    - name: Set up Node.js for security scanning
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Run npm audit on frontend
      working-directory: ./frontend
      run: npm audit --audit-level=high